sonar.organization=raffaello-github
sonar.projectKey=Raffaello_hyper-sonic-drivers

sonar.sources=hyper-sonic-drivers/src,hyper-sonic-drivers/examples
sonar.tests=hyper-sonic-drivers/test
#sonar.cfamily.build-wrapper-output=build/bw-output
sonar.cfamily.threads=2
sonar.cfamily.cache.enabled=false
sonar.cxx.xunit.reportPaths=build/
sonar.cfamily.gcov.reportsPath=build/
# sonar.cfamily.llvm-cov.reportPath=build/
sonar.coverageReportPaths=build/coverage.xml
