#pragma once

#include <cstdint>
#include <memory>
#include <functional>
#include <optional>
#include <HyperSonicDrivers/audio/IMixer.hpp>
#include <HyperSonicDrivers/audio/mixer/ChannelGroup.hpp>
#include <HyperSonicDrivers/audio/IAudioStream.hpp>

namespace HyperSonicDrivers::hardware
{
    typedef std::function<void()> TimerCallBack;

    constexpr int FIXP_SHIFT = 16;

    class IHardware
    {
    public:
        IHardware(IHardware&) = delete;
        IHardware(IHardware&&) = delete;
        IHardware& operator=(IHardware&) = delete;

        IHardware(const std::shared_ptr<audio::IMixer>& mixer);
        virtual ~IHardware();

        inline bool isInit() const noexcept { return m_init; }

        virtual bool isStereo() const noexcept = 0;
        virtual bool init() = 0;
        virtual void reset() = 0;

        virtual void start(
            const std::shared_ptr<TimerCallBack>& callback,
            const audio::mixer::eChannelGroup group,
            const uint8_t volume,
            const uint8_t pan,
            const int timerFrequency);

        void stop();

        virtual uint32_t setCallbackFrequency(const int timerFrequency);
        inline std::shared_ptr<audio::IMixer> getMixer() const noexcept { return m_mixer; };
        inline std::optional<uint8_t> getChannelId() const noexcept { return m_channelId; };

    protected:
        virtual void startCallbacks(
            const audio::mixer::eChannelGroup group,
            const uint8_t volume,
            const uint8_t pan,
            const int timerFrequency
        ) = 0;

        void stopCallbacks();
        void callCallback();

        /**
        * get the audio stream generated by the OPL
        **/
        virtual std::shared_ptr<audio::IAudioStream> getAudioStream() const noexcept = 0;

        bool m_init = false;
        std::shared_ptr<audio::IMixer> m_mixer;
        std::optional<uint8_t> m_channelId;
    private:
        std::shared_ptr<TimerCallBack> m_callback;
    };
}
