#ifndef __VERSION_H__
#define __VERSION_H__

#define __SONIC_DRIVERS_VERSION "0.6.0"
#define __SONIC_DRIVERS_VERSION_MAJOR 0
#define __SONIC_DRIVERS_VERSION_MINOR 6
#define __SONIC_DRIVERS_VERSION_PATCH 0

#endif
