name: autoPublish
## TODO to be triggered by checkVersion
## TODO: it could be done as another job/step in checkversion ?
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - '.gitignore'
      - '.gitattributes'
      - 'README.md'
      - 'LICENSE'
      - 'wave_generators.r'

jobs:
  build:
    name: autoPublish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: publishVersion
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          set -e
          VER=$(cat CMakeLists.txt  | grep " VERSION " | cut -d ' ' -f 4)
          echo "VER: ${VER}"
          gh release create v${VER} -d --generate-notes

