### reusable workflow can't be called with a strategy matrix
### and so are not used as a workflow without a strategy matrix
### to feed in inputs parameters is useless in my case.

### Sonar cloud job the cache in $HOME/.sonar doesn't save sub-dirs
### so can't be cached.

name: ci-linux
on:
  release:
    types: [created]
  pull_request:
    branches: [master]
    paths-ignore:
      - "doc/**"
      - ".gitignore"
      - ".gitattributes"
      - "README.md"
      - "LICENSE"
      - "wave_generators.r"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        use_mt32: [USE_MT32=ON]
        use_sdl: [USE_SDL3=OFF, USE_SDL3=ON, USE_SDL2=ON]
    name: Build Linux
    runs-on: ubuntu-24.04
    steps:
      - name: set-up environment variables
        run: |
          echo "ARCH=64" >> $GITHUB_ENV
          #echo "CMAKE_A=x64" >> $GITHUB_ENV
      - name: install MT32Emu
        run: |
          cd /tmp
          git clone https://github.com/munt/munt.git
          cd munt && cd mt32emu
          cmake -DCMAKE_BUILD_TYPE:STRING=Release . && make && sudo make install
        if: matrix.use_mt32 == 'USE_MT32=ON'
      - name: install other dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y \
            libgtest-dev \
            libgmock-dev \
            libsdl2-dev \
            libsdl3-dev
      - uses: actions/checkout@v4
      - name: create build dir
        run: mkdir build
      - name: cmake generator
        run: |
          cmake -D${{ matrix.use_mt32 }} -D${{ matrix.use_sdl }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        working-directory: build
      - name: cmake build
        run: |
          cmake --build . --config=${{ matrix.build_type }} -j4
        working-directory: build
      - name: CTest
        run: ctest --output-on-failure
        working-directory: build
      - name: cmake install
        run: sudo cmake --build . --target install --config ${{ matrix.build_type }} -j4
        working-directory: build
      - name: cmake package
        run: sudo cmake --build . --target package --config ${{ matrix.build_type }} -j4
        working-directory: build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          prerelease: false
          files: "build/*.zip"
