name: ci
on: [ push ]
    
  #pull_request:
  #  branches: [ master ]

permissions: read-all

jobs:
  #vcpkg-dep:
  #  name: vcpkg dependecies
  #  runs-on: windows-2019
  #  steps:
  build:
    name: Build win
    runs-on: windows-2019
    #needs: vcpkg-dep
    steps:
      - uses: actions/cache@v2
        id: dep-cache
        with:
            path: |
              C:\vcpkg\installed
              C:\ProgramData\chocolatey\lib\ninja
            key: ${{ runner.os }}-dep-cache-${{ hashFiles('**/*') }}
            restore-keys: ${{ runner.os }}-dep-cache
      - name: vcpkg
        #if: steps.dep-cache.outputs.cache-hit != 'true'
        run: |
          . "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          vcpkg install sdl2 --triplet=x86-windows
      - name: install Ninja
        run: choco install ninja
      
      - name: debug
        run: ninja --version

      - uses: actions/checkout@v2
      - name: create build dir
        run: mkdir build
      - name: cmake
        run: |
          . "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cmake -G"Ninja" -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug ..
        working-directory: build
